### ISSUE TITLE
Partial/malformed JSON-based serialisations of models containing 'AttributeType' identified by external URIs

### ISSUE THREAD

**Issue by StatelessCat** [ktbs/ktbs#51]
Hey,
Posting a model like this one: 

``` turtle
@prefix : <http://liris.cnrs.fr/silex/2009/ktbs#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
<.> :contains <m1> .
<m1> a :TraceModel .
<#xapiStatement> a :ObselType .
<http://semweb.mmlab.be/ns/tincan2prov/version> a :AttributeType ;
  :hasAttributeDomain <#xapiStatement> ;
  :hasAttributeRange xsd:string .
```

The kTBS seems happy with that and anwser 201.
Doing a GET for a `application/turtle` lead to an expected representation.
Doing a GET for a {`application/json`, `application/ld+json`} lead to a 
partial/malformed response, because, I think, of the assert that
that URI of a kTBS's `AttributeType` must start with the kTBS's root URI.
(full stacktrace is shown below).

Do you think saying that 
`<http://semweb.mmlab.be/ns/tincan2prov/version> a :AttributeType ;`
is «Linked-Data compliant» and semantically correct ? 

Thanks.

``` curl
$ curl http://localhost:8001/base1/m1 -vv
*   Trying ::1...
* connect to ::1 port 8001 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8001 (#0)
> GET /base1/m1 HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.43.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Mon, 09 May 2016 20:39:58 GMT
< Server: WSGIServer/0.1 Python/2.7.11
< vary: accept
< content-type: application/ld+json
< content-location: http://localhost:8001/base1/m1.jsonld
< etag: W/"application/ld+json/96f3eb3222b369152206a0f237a5a601"
< last-modified: Mon, 09 May 2016 19:38:23 GMT
< Cache-Control: max-age=1847
< 
{
    "@context": "http://liris.cnrs.fr/silex/2011/ktbs-jsonld-context",
    "@graph": [
        {
            "@id": "http://localhost:8001/base1/m1",
            "@type": "TraceModel",
            "inBase": "./" ,
            "hasUnit": "millisecond" 
        },
        {
            "@id": "#xapiStatement" ,
* Closing connection 0
            "@type": "ObselType" raphael ~/code/xapi-to-ktbs $ 
```

``` Python
127.0.0.1 - - [09/May/2016 21:41:46] "GET /base1/m1 HTTP/1.1" 200 14335
127.0.0.1 - - [09/May/2016 21:41:46] "GET /base1/m1?_=1462822906545 HTTP/1.1" 200 346
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/serpar/jsonld_serializers.py", line 39, in wrapped
    for i in func(*args, **kw):
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/serpar/jsonld_serializers.py", line 477, in serialize_json_model
    for atype in tmodel.iter_attribute_types(False):
  File "/home/raphael/ktbs-env-dev/ktbs/lib/ktbs/api/trace_model.py", line 113, in iter_attribute_types
    yield factory(uri, [KTBS.AttributeType])
  File "/home/raphael/ktbs-env-dev/ktbs/lib/rdfrest/cores/local.py", line 548, in factory
    assert uri.startswith(self.service.root_uri), uri
AssertionError: http://semweb.mmlab.be/ns/tincan2prov/version
127.0.0.1 - - [09/May/2016 21:41:46] "GET /base1/m1?_=1462822906545 HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43176)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

kTBS version «affected»: 

```
commit:  db62930bde3ac253079766090bd837bb2669d83d
```

**Comment by pchampin** [comment]
The problem here is twofold:

* The POSTed turtle is ill-formed. Relative IRI `<#xapiStatement>` should be `<m1#xapiStatement>` (because the base IRI of the POST is the target of the HTTP request, hence the IRI of the Base). This is why the resulting Turtle (when you GET the model) looks strange, but it is consistent with what has been posted.

* Since the model is oddly formed, the JSON serializer crashes. This is a separate (and well known) bug, registered as #77.
